version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/eradication_data_requirements:latest
    command: bash
    volumes:
      - $PWD:/workdir